version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  frontend:
    build: ./Front-end
    container_name: frontend
    restart: always
    expose:
      - 3000

  backend:
    build: ./Back-end
    container_name: backend
    restart: always
    expose:
      - 8888
    environment:
      - TMDB_TOKEN=${TMDB_TOKEN}

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

